spring:
  application:
    name: batch
  datasource-data:
    username: root
    password: 1234
    jdbc-url: jdbc:mysql://localhost:3306/batch?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-meta:
    username: root
    password: 1234
    jdbc-url: jdbc:mysql://localhost:3306/meta_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false # 서버 재시작시 배치 자동실행 방지
